name: user_repository
description: Dart package which manages the user domain.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.3
  meta: 1.1.8
  uuid: ^2.2.0

  flutter_bloc: ^6.0.0

  firebase_core: ^0.4.5         # Firebase Core API which enable connecting multiple Firebase apps.
  google_sign_in: ^4.5.1        # For Google Sign In
  firebase_auth: ^0.16.1        # Use Firebase Authentication API
  rxdart: ^0.24.1               # Additional use Dart Streams and StreamControllers
  font_awesome_flutter: ^8.8.1  # font icon pack